// user profile
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

// Departments
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const GETTING_DEPARTMENTS = 'GETTING_DEPARTMENTS';
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
export const CREATING_DEPARTMENT = 'GETTING_DEPARTMENTS';
export const DEPARTMENTS_ERROR = 'DEPARTMENTS_ERROR';

// Groups
export const GET_GROUPS = 'GET_GROUPS';
export const GETTING_GROUPS = 'GETTING_GROUPS';
export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATING_GROUP = 'CREATING_GROUP';
export const GROUPS_ERROR = 'GROUPS_ERROR';

// Shifts
export const GET_SHIFTS = 'GET_SHIFTS';
export const GETTING_SHIFTS = 'GETTING_SHIFTS';
export const GET_SHIFT_DETAILS = 'GET_SHIFT_DETAILS';
export const GETTING_SHIFT_DETAILS = 'GETTING_SHIFT_DETAILS';
export const CREATE_SHIFT = 'CREATE_SHIFT';
export const CREATING_SHIFT = 'CREATING_SHIFT';
export const UPDATE_SHIFT = 'UPDATE_SHIFT';
export const UPDATING_SHIFT = 'UPDATING_SHIFT';
export const SHIFTS_ERROR = 'SHIFTS_ERROR';

// Designations
export const GET_DESIGNATIONS = 'GET_DESIGNATIONS';
export const GETTING_DESIGNATIONS = 'GETTING_DESIGNATIONS';
export const CREATE_DESIGNATION = 'CREATE_DESIGNATION';
export const CREATING_DESIGNATION = 'CREATING_DESIGNATION';
export const DESIGNATIONS_ERROR = 'DESIGNATIONS_ERROR';

// Employees
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GETTING_EMPLOYEES = 'GETTING_EMPLOYEES';
export const INVITE_EMPLOYEE = 'INVITE_EMPLOYEE';
export const INVITING_EMPLOYEE = 'INVITING_EMPLOYEE';
export const SIGNUP_EMPLOYEE = 'SIGNUP_EMPLOYEE';
export const SIGNING_UP_EMPLOYEE = 'SIGNING_UP_EMPLOYEE';
export const EMPLOYEES_ERROR = 'EMPLOYEES_ERROR';

// Errors
export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// Success
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'
export const CLEAR_SUCCESS_MESSAGE = 'CLEAR_SUCCESS_MESSAGE'